export const GET_CATEGORIES = "GET_CATEGORIES"
export const LOAD_DATA_SUCCESS = "LOAD_DATA_SUCCESS"
export const GET_PRODUCT_BY_CATEGORY = "GET_PRODUCT_BY_CATEGORY";
export const ADD_ITEM_CART = "ADD_ITEM_CART";
export const ADD_ITEM_CART_SUCCESS = "ADD_ITEM_CART_SUCCESS";

export const CLEAR_ITEM_CART = "CLEAR_ITEM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const GET_TOP_PRODUCT = "GET_TOP_PRODUCT";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS"
export const SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS";
