const city = [
  {
    idCity: 1,
    nameCity: "Hồ chí Minh",
  },
  {
    idCity: 1,
    nameCity: "Hà Nội",
  },
];
const district = [
  {
    idDistrct: 1,
    idCity: 1,
    nameCity: "Go Vap",
  },
  {
    idDistrct: 2,
    idCity: 1,
    nameCity: "Phu Nhuan",
  },
  {
    idDistrct: 3,
    idCity: 2,
    nameCity: "Hang Buom",
  },
  {
    idDistrct: 4,
    idCity: 2,
    nameCity: "Pho Ha Noi",
  },
];
const ward = [
  {
    idWard: 1,
    idDistrct: 1,
    nameCity: "Go Vap w",
  },
  {
    idWard: 2,
    idDistrct: 1,
    nameCity: "Phu Nhuan w",
  },
  {
    idWard: 3,
    idDistrct: 2,
    nameCity: "Hang Buom w",
  },
  {
    idDistrct: 4,
    idDistrct: 2,
    nameCity: "Pho Ha Noi w",
  },
];
const testItem = [
  {
    id: "1",
    name: "testa",
    cungcap: "dulichaa",
    price: "100000",
    coc: "10000",
    songay: 1,
    soluong: 1,
    image: "https://9mobi.vn/cf/images/2015/03/nkk/hinh-dep-1.jpg",
  },
  {
    id: "2",
    name: "testb",
    cungcap: "dulichaa",
    price: "100000",
    coc: "10000",
    songay: 1,
    soluong: 2,
    image: "https://i.9mobi.vn/cf/images/2015/03/nkk/hinh-dep-3.jpg",
  },
  {
    id: "2",
    name: "testb",
    cungcap: "dulichaa",
    price: "100000",
    coc: "10000",
    songay: 1,
    soluong: 2,
    image: "https://i.9mobi.vn/cf/images/2015/03/nkk/hinh-dep-3.jpg",
  },
  {
    id: "2",
    name: "testb",
    cungcap: "dulichaa",
    price: "100000",
    coc: "10000",
    songay: 1,
    soluong: 2,
    image: "https://i.9mobi.vn/cf/images/2015/03/nkk/hinh-dep-3.jpg",
  },
  {
    id: "2",
    name: "testb",
    cungcap: "dulichaa",
    price: "100000",
    coc: "10000",
    songay: 1,
    soluong: 2,
    image: "https://i.9mobi.vn/cf/images/2015/03/nkk/hinh-dep-3.jpg",
  },
  {
    id: "2",
    name: "testb",
    cungcap: "dulichaa",
    price: "100000",
    coc: "10000",
    songay: 1,
    soluong: 2,
    image: "https://i.9mobi.vn/cf/images/2015/03/nkk/hinh-dep-3.jpg",
  },
  {
    id: "2",
    name: "testb",
    cungcap: "dulichaa",
    price: "100000",
    coc: "10000",
    songay: 1,
    soluong: 2,
    image: "https://i.9mobi.vn/cf/images/2015/03/nkk/hinh-dep-3.jpg",
  },
  {
    id: "2",
    name: "testb",
    cungcap: "dulichaa",
    price: "100000",
    coc: "10000",
    songay: 1,
    soluong: 2,
    image: "https://i.9mobi.vn/cf/images/2015/03/nkk/hinh-dep-3.jpg",
  },
  {
    id: "2",
    name: "testb",
    cungcap: "dulichaa",
    price: "100000",
    coc: "10000",
    songay: 1,
    soluong: 2,
    image: "https://i.9mobi.vn/cf/images/2015/03/nkk/hinh-dep-3.jpg",
  },
  {
    id: "2",
    name: "testb",
    cungcap: "dulichaa",
    price: "100000",
    coc: "10000",
    songay: 1,
    soluong: 2,
    image: "https://i.9mobi.vn/cf/images/2015/03/nkk/hinh-dep-3.jpg",
  },
  {
    id: "2",
    name: "testb",
    cungcap: "dulichaa",
    price: "100000",
    coc: "10000",
    songay: 1,
    soluong: 2,
    image: "https://i.9mobi.vn/cf/images/2015/03/nkk/hinh-dep-3.jpg",
  },
  {
    id: "2",
    name: "testb",
    cungcap: "dulichaa",
    price: "100000",
    coc: "10000",
    songay: 1,
    soluong: 2,
    image: "https://i.9mobi.vn/cf/images/2015/03/nkk/hinh-dep-3.jpg",
  },
  {
    id: "2",
    name: "testb",
    cungcap: "dulichaa",
    price: "100000",
    coc: "10000",
    songay: 1,
    soluong: 2,
    image: "https://i.9mobi.vn/cf/images/2015/03/nkk/hinh-dep-3.jpg",
  },
  {
    id: "2",
    name: "testb",
    cungcap: "dulichaa",
    price: "100000",
    coc: "10000",
    songay: 1,
    soluong: 2,
    image: "https://i.9mobi.vn/cf/images/2015/03/nkk/hinh-dep-3.jpg",
  },
  {
    id: "2",
    name: "testb",
    cungcap: "dulichaa",
    price: "100000",
    coc: "10000",
    songay: 1,
    soluong: 2,
    image: "https://i.9mobi.vn/cf/images/2015/03/nkk/hinh-dep-3.jpg",
  },
  {
    id: "2",
    name: "testb",
    cungcap: "dulichaa",
    price: "100000",
    coc: "10000",
    songay: 1,
    soluong: 2,
    image: "https://i.9mobi.vn/cf/images/2015/03/nkk/hinh-dep-3.jpg",
  },
  {
    id: "2",
    name: "testb",
    cungcap: "dulichaa",
    price: "100000",
    coc: "10000",
    songay: 1,
    soluong: 2,
    image: "https://i.9mobi.vn/cf/images/2015/03/nkk/hinh-dep-3.jpg",
  },
];
export  {
    city,ward,district,testItem
}